@CV_Generator_HostAddress = http://localhost:5087

GET http://localhost:5087/cv

###

GET http://localhost:5087/cv/home

###

GET http://localhost:5087/cv/login

###

GET http://localhost:5087/cv/register

###

GET http://localhost:5087/cv/generatecv

###

// Dont Clicked This Many time, Its sensitive
POST http://localhost:5087/cv/sendemail
Content-Type: application/json"

{   
    "subject": "Test",
    "name": "Test User", 
    "email": "test@example.com", 
    "question": "Test question"
}
###

POST http://localhost:5087/cv/auth/register
Content-Type: application/json"

{
    "Username": "Hafizcse12",
    "Email": "hafizcse@gmail12.com",
    "Password": "hafiz12345",
    "ConfirmPassword": "hafiz12345"
}
###

POST http://localhost:5087/cv/auth/login
Content-Type: application/json"

{
    "Username": "Hafizcse",
    "Password": "hafiz12345"
}
###


